# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: open_project.proto for package ''

require 'grpc'
require 'app/proto/open_project_pb'

module OpService
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'OpService'

    rpc :SendMessage, ::MessageRequest, ::Result
    rpc :GetTemplates, ::Google::Protobuf::Empty, ::GetTemplateResp
  end

  Stub = Service.rpc_stub_class
end
