allowBuilds:
  '@parcel/watcher': true
  core-js: true
  core-js-pure: true
  es5-ext: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  th-analytics: true

minimumReleaseAgeExclude:
  - '@angular-devkit/core@21.2.12'
  - '@angular-devkit/schematics@21.2.12'
  - '@schematics/angular@21.2.12'

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - core-js-pure
  - es5-ext
  - esbuild
  - highlight.js
  - lmdb
  - msgpackr-extract
  - nice-napi
