name: "Frontend test suite"

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - release/*
    paths:
      - '**/frontend/**/*.ts'
      - '**/frontend/**/*.js'
      - '**/frontend/**/*.json'

  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '**/frontend/**/*.ts'
      - '**/frontend/**/*.js'
      - '**/frontend/**/*.json'

permissions:
  contents: read

defaults:
  run:
    working-directory: ./frontend

jobs:
  units:
    name: Units
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.33.0
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version: '22.15'
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install Dependencies
        id: pnpm-install
        run: pnpm install --frozen-lockfile

      - name: Register plugins
        id: pnpm-run-ci-plugins-register-frontend
        run: pnpm run ci:plugins:register_frontend

      - name: Test (Angular)
        id: pnpm-test
        run: pnpm test -- --code-coverage
